version: '3'
services:
    app:
        build: .
        container_name: mastodon-to-bluesky
        env_file: '.env'
        volumes:
            - mastodon-to-bluesky:/usr/src/app/data
        restart: unless-stopped

volumes:
    mastodon-to-bluesky:
