version: '3'
services:
    app:
        image: host/mastodon-to-bluesky:latest
        container_name: mastodon-to-bluesky
        environment:
            MASTODON_INSTANCE: 'https://mastodon.instance'
            MASTODON_USER: 'username'
            BLUESKY_ENDPOINT: 'https://bsky.social'
            BLUESKY_HANDLE: 'USERNAME.bsky.social'
            BLUESKY_PASSWORD: 'PASSWORD'
            INTERVAL_MINUTES: 5
        volumes:
            - mastodon-to-bluesky:/usr/src/app/data
        restart: unless-stopped

volumes:
  mastodon-to-bluesky:
    external: true